namespace FieldCure.AssistStudio.Models;

/// <summary>
/// Reports token consumption for an AI request, including input and output counts.
/// </summary>
/// <param name="InputTokens">The number of tokens in the prompt (input).</param>
/// <param name="OutputTokens">The number of tokens generated by the model (output).</param>
public partial record TokenUsage(
    int InputTokens,
    int OutputTokens
)
{
    #region Computed Properties

    /// <summary>The combined total of input and output tokens.</summary>
    public int TotalTokens => InputTokens + OutputTokens;

    #endregion
}
