using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace FieldCure.AssistStudio.Models;

/// <summary>
/// Specifies the role of a participant in a chat conversation.
/// </summary>
public enum ChatRole
{
    /// <summary>A message from the end user.</summary>
    User,

    /// <summary>A message generated by the AI assistant.</summary>
    Assistant,

    /// <summary>A system-level instruction that guides the assistant's behavior.</summary>
    System
}

/// <summary>
/// Represents a single message in a chat conversation, with support for property change notifications and streaming.
/// </summary>
public partial class ChatMessage : INotifyPropertyChanged
{
    private string _content;
    private bool _isStreaming;

    /// <summary>
    /// Initializes a new <see cref="ChatMessage"/> with the specified role and optional content.
    /// </summary>
    /// <param name="role">The role of the message sender.</param>
    /// <param name="content">The initial text content of the message.</param>
    public ChatMessage(ChatRole role, string content = "")
    {
        Id = Guid.NewGuid().ToString("N");
        Role = role;
        _content = content;
        Timestamp = DateTime.UtcNow;
        Attachments = [];
    }

    /// <summary>A unique identifier for this message.</summary>
    public string Id { get; }

    /// <summary>The role of the message sender (User, Assistant, or System).</summary>
    public ChatRole Role { get; }

    /// <summary>The text content of the message. Raises <see cref="PropertyChanged"/> when updated.</summary>
    public string Content
    {
        get => _content;
        set => SetField(ref _content, value);
    }

    /// <summary>Indicates whether the message is currently being streamed from the provider.</summary>
    public bool IsStreaming
    {
        get => _isStreaming;
        set => SetField(ref _isStreaming, value);
    }

    /// <summary>The UTC timestamp when this message was created.</summary>
    public DateTime Timestamp { get; }

    /// <summary>File attachments included with this message.</summary>
    public IReadOnlyList<ChatAttachment> Attachments { get; init; }

    /// <summary>
    /// Provider name that generated this message (e.g., "Claude", "OpenAI").
    /// </summary>
    public string? ProviderName { get; init; }

    /// <summary>
    /// Model ID used to generate this message (e.g., "claude-sonnet-4-20250514").
    /// </summary>
    public string? ProviderModelId { get; init; }

    /// <inheritdoc/>
    public event PropertyChangedEventHandler? PropertyChanged;

    private void SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return;
        field = value;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
