using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace FieldCure.Ai.Providers.Models;

/// <summary>
/// Specifies the role of a participant in a chat conversation.
/// </summary>
public enum ChatRole
{
    /// <summary>A message from the end user.</summary>
    User,

    /// <summary>A message generated by the AI assistant.</summary>
    Assistant,

    /// <summary>A system-level instruction that guides the assistant's behavior.</summary>
    System,

    /// <summary>A tool result message containing the output of a tool invocation.</summary>
    Tool
}

/// <summary>
/// Why an assistant message stopped streaming. Persisted on the message and used
/// by the renderer to decorate the bubble footer (e.g. <c>"Stopped · 12.3s"</c>).
/// </summary>
public enum StopReason
{
    /// <summary>Default: the model finished naturally (end_turn / stop_sequence / etc.).</summary>
    Completed,

    /// <summary>The user pressed STOP before the stream completed.</summary>
    UserCanceled,

    /// <summary>The provider cut the response short at its max_tokens limit.</summary>
    MaxTokens,
}

/// <summary>
/// Represents a single message in a chat conversation, with support for property change notifications and streaming.
/// </summary>
public partial class ChatMessage : INotifyPropertyChanged
{
    #region Fields

    /// <summary>Backing field for <see cref="Content"/>.</summary>
    private string _content;

    /// <summary>Backing field for <see cref="IsStreaming"/>.</summary>
    private bool _isStreaming;

    /// <summary>Backing field for <see cref="ThinkingContent"/>.</summary>
    private string? _thinkingContent;

    /// <summary>Backing field for <see cref="ToolMedia"/>; lazily allocated on first append.</summary>
    private List<MediaContent>? _toolMedia;

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new <see cref="ChatMessage"/> with the specified role and optional content.
    /// </summary>
    public ChatMessage(ChatRole role, string content = "")
    {
        Id = Guid.NewGuid().ToString("N");
        Role = role;
        _content = content;
        Timestamp = DateTime.UtcNow;
        Attachments = [];
    }

    /// <summary>
    /// Initializes a <see cref="ChatMessage"/> with an existing ID (for restoring saved conversations).
    /// </summary>
    public ChatMessage(string id, ChatRole role, string content = "")
    {
        Id = id;
        Role = role;
        _content = content;
        Timestamp = DateTime.UtcNow;
        Attachments = [];
    }

    #endregion

    #region Properties

    /// <summary>A unique identifier for this message.</summary>
    public string Id { get; }

    /// <summary>The role of the message sender (User, Assistant, or System).</summary>
    public ChatRole Role { get; }

    /// <summary>The text content of the message. Raises <see cref="PropertyChanged"/> when updated.</summary>
    /// <remarks>
    /// INVARIANT: This property stores raw markdown as authored or streamed.
    /// Rendering (e.g. via marked.js in WebView2) is one-directional; rendered
    /// HTML must never be written back to this property.
    /// <see cref="Export.MarkdownExporter"/> relies on this invariant to produce lossless exports.
    /// </remarks>
    public string Content
    {
        get => _content;
        set => SetField(ref _content, value);
    }

    /// <summary>Indicates whether the message is currently being streamed from the provider.</summary>
    public bool IsStreaming
    {
        get => _isStreaming;
        set => SetField(ref _isStreaming, value);
    }

    /// <summary>The UTC timestamp when this message was created.</summary>
    public DateTime Timestamp { get; init; }

    /// <summary>File attachments included with this message.</summary>
    public IReadOnlyList<ChatAttachment> Attachments { get; init; }

    /// <summary>
    /// Provider name that generated this message (e.g., "Claude", "OpenAI").
    /// </summary>
    public string? ProviderName { get; init; }

    /// <summary>
    /// Model ID used to generate this message (e.g., "claude-sonnet-4-6").
    /// </summary>
    public string? ProviderModelId { get; init; }

    /// <summary>
    /// Tool calls requested by the assistant in this message. Only set for <see cref="ChatRole.Assistant"/> messages.
    /// Mutable so SDK consumers can attach tool calls after a streaming turn completes —
    /// the stream surfaces tool calls via <c>StreamResult.ToolCalls</c>, and the consumer's
    /// multi-turn loop assigns them here before issuing the follow-up request so the
    /// converter can emit the matching <c>tool_use</c> blocks.
    /// </summary>
    public IReadOnlyList<ToolCall>? ToolCalls { get; set; }

    /// <summary>
    /// The ID of the tool call this message is a result for. Only set for <see cref="ChatRole.Tool"/> messages.
    /// </summary>
    public string? ToolCallId { get; init; }

    /// <summary>
    /// Media content attached to this message: tool execution results on a Tool message,
    /// or assistant-generated inline media (e.g., Gemini image-generation output) on an
    /// Assistant message. Used for persistence in .astx files.
    /// Mutable so streaming providers can append while a response is in flight.
    /// </summary>
    public IReadOnlyList<MediaContent>? ToolMedia
    {
        get => _toolMedia;
        init => _toolMedia = value is null ? null : [.. value];
    }

    /// <summary>
    /// Appends a media item to <see cref="ToolMedia"/>, allocating the backing list on first call.
    /// Raises <see cref="PropertyChanged"/> for <see cref="ToolMedia"/>.
    /// </summary>
    public void AppendToolMedia(MediaContent media)
    {
        _toolMedia ??= [];
        _toolMedia.Add(media);
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(ToolMedia)));
    }

    /// <summary>
    /// Raw <c>structuredContent</c> from an MCP tool result (MCP spec
    /// <c>CallToolResult.structuredContent</c>), preserved verbatim as a
    /// <see cref="JsonElement"/>. Unlike <see cref="Content"/>, this never
    /// entered the model's context — it is a host-side rendering channel.
    /// The chat panel inspects it for renderable payloads (today: a
    /// <c>chart</c> object such as a Plotly spec from <c>ls_get_chart</c>);
    /// keeping the whole blob means future structured-render features need
    /// no new field. Only set for <see cref="ChatRole.Tool"/> messages whose
    /// tool returned structured content. Persisted in <c>.astx</c> files;
    /// omitted from JSON when absent for backwards-compat with older files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? StructuredContent { get; init; }

    /// <summary>
    /// Thinking/reasoning content from the AI model (e.g., Claude extended thinking).
    /// Raises <see cref="PropertyChanged"/> when updated.
    /// </summary>
    public string? ThinkingContent
    {
        get => _thinkingContent;
        set => SetField(ref _thinkingContent, value);
    }

    /// <summary>
    /// Elapsed time in seconds for generating this assistant response.
    /// Measured from streaming start to completion. Null when not measured.
    /// </summary>
    public double? ElapsedSeconds { get; set; }

    /// <summary>
    /// Total token count for this assistant response (input + output).
    /// Null for non-assistant messages or when not reported by the provider.
    /// </summary>
    public int? TokenCount { get; set; }

    /// <summary>
    /// Summary metadata. Non-null indicates this message is a conversation summary
    /// that replaces the covered messages during prompt building.
    /// Only meaningful for <see cref="ChatRole.Assistant"/> messages.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SummaryMeta? Summary { get; init; }

    /// <summary>
    /// True for messages the host inserts as part of an internal flow (e.g. the
    /// "Continue writing from where you left off." user turn appended when the
    /// user clicks the Continue button on a truncated assistant response).
    /// Hidden messages MUST be sent to the provider as part of the prompt — they
    /// shape the next assistant turn — but MUST NOT render as a chat bubble in
    /// the UI. Persisted in <c>.astx</c> so the conversation tree round-trips
    /// without the renderer suddenly showing a stray "Continue" bubble after
    /// reload. Default <c>false</c> is omitted from JSON for backwards-compat
    /// with existing files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool IsHidden { get; init; }

    /// <summary>
    /// True for assistant messages that continue an earlier truncated response
    /// (the user clicked Continue). The renderer prefixes a small "↪ continued"
    /// label so the new bubble visually links back to the prior one. Persisted
    /// so reload restores the marker; default <c>false</c> omitted from JSON.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool IsContinuation { get; init; }

    /// <summary>
    /// Why this assistant turn stopped. Defaults to <see cref="Models.StopReason.Completed"/>
    /// (clean end-of-turn). The renderer uses this to render footer prefixes such as
    /// <c>"Stopped · 12.3s"</c> for <see cref="Models.StopReason.UserCanceled"/> or
    /// <c>"truncated"</c> on reload of <see cref="Models.StopReason.MaxTokens"/> turns.
    /// Persisted so reload restores the marker; default <c>Completed</c> omitted from JSON.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(JsonStringEnumConverter<StopReason>))]
    public StopReason StopReason { get; set; } = StopReason.Completed;

    /// <summary>
    /// Convenience read-only alias for <c>StopReason == MaxTokens</c>. Drives the
    /// live Continue button and the reload-time "truncated" hint. Setters were
    /// removed in v3; callers now write <see cref="StopReason"/> directly.
    /// Not persisted — <see cref="StopReason"/> is the single source of truth.
    /// </summary>
    [JsonIgnore]
    public bool IsTruncated => StopReason == StopReason.MaxTokens;

    #endregion

    #region Tree Properties

    /// <summary>
    /// The ID of the parent message in the conversation tree.
    /// Null for the first message (root). Used for branching support.
    /// </summary>
    public string? ParentId { get; init; }

    /// <summary>
    /// Total number of sibling messages sharing the same parent.
    /// Computed at runtime, not serialized.
    /// </summary>
    [JsonIgnore]
    public int SiblingCount { get; set; } = 1;

    /// <summary>
    /// Zero-based index among siblings sharing the same parent.
    /// Computed at runtime, not serialized.
    /// </summary>
    [JsonIgnore]
    public int SiblingIndex { get; set; }

    /// <summary>
    /// The ID of the currently active child in a branch.
    /// Used to preserve the user's branch selection across save/load.
    /// Serialized when non-null so branch navigation is restored correctly.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ActiveChildId { get; set; }

    #endregion

    #region INotifyPropertyChanged

    /// <inheritdoc/>
    public event PropertyChangedEventHandler? PropertyChanged;

    #endregion

    #region Private Methods

    /// <summary>Sets a backing field and raises <see cref="PropertyChanged"/> if the value changed.</summary>
    private void SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return;
        field = value;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    #endregion
}
