using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;

namespace FieldCure.Ai.Providers.Models;

/// <summary>
/// Specifies the role of a participant in a chat conversation.
/// </summary>
public enum ChatRole
{
    /// <summary>A message from the end user.</summary>
    User,

    /// <summary>A message generated by the AI assistant.</summary>
    Assistant,

    /// <summary>A system-level instruction that guides the assistant's behavior.</summary>
    System,

    /// <summary>A tool result message containing the output of a tool invocation.</summary>
    Tool
}

/// <summary>
/// Represents a single message in a chat conversation, with support for property change notifications and streaming.
/// </summary>
public partial class ChatMessage : INotifyPropertyChanged
{
    #region Fields

    /// <summary>Backing field for <see cref="Content"/>.</summary>
    private string _content;

    /// <summary>Backing field for <see cref="IsStreaming"/>.</summary>
    private bool _isStreaming;

    /// <summary>Backing field for <see cref="ThinkingContent"/>.</summary>
    private string? _thinkingContent;

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new <see cref="ChatMessage"/> with the specified role and optional content.
    /// </summary>
    public ChatMessage(ChatRole role, string content = "")
    {
        Id = Guid.NewGuid().ToString("N");
        Role = role;
        _content = content;
        Timestamp = DateTime.UtcNow;
        Attachments = [];
    }

    /// <summary>
    /// Initializes a <see cref="ChatMessage"/> with an existing ID (for restoring saved conversations).
    /// </summary>
    public ChatMessage(string id, ChatRole role, string content = "")
    {
        Id = id;
        Role = role;
        _content = content;
        Timestamp = DateTime.UtcNow;
        Attachments = [];
    }

    #endregion

    #region Properties

    /// <summary>A unique identifier for this message.</summary>
    public string Id { get; }

    /// <summary>The role of the message sender (User, Assistant, or System).</summary>
    public ChatRole Role { get; }

    /// <summary>The text content of the message. Raises <see cref="PropertyChanged"/> when updated.</summary>
    public string Content
    {
        get => _content;
        set => SetField(ref _content, value);
    }

    /// <summary>Indicates whether the message is currently being streamed from the provider.</summary>
    public bool IsStreaming
    {
        get => _isStreaming;
        set => SetField(ref _isStreaming, value);
    }

    /// <summary>The UTC timestamp when this message was created.</summary>
    public DateTime Timestamp { get; init; }

    /// <summary>File attachments included with this message.</summary>
    public IReadOnlyList<ChatAttachment> Attachments { get; init; }

    /// <summary>
    /// Provider name that generated this message (e.g., "Claude", "OpenAI").
    /// </summary>
    public string? ProviderName { get; init; }

    /// <summary>
    /// Model ID used to generate this message (e.g., "claude-sonnet-4-20250514").
    /// </summary>
    public string? ProviderModelId { get; init; }

    /// <summary>
    /// Tool calls requested by the assistant in this message. Only set for <see cref="ChatRole.Assistant"/> messages.
    /// </summary>
    public IReadOnlyList<ToolCall>? ToolCalls { get; init; }

    /// <summary>
    /// The ID of the tool call this message is a result for. Only set for <see cref="ChatRole.Tool"/> messages.
    /// </summary>
    public string? ToolCallId { get; init; }

    /// <summary>
    /// Media content from tool execution results (images, audio, video).
    /// Set when a tool returns multimedia alongside text. Used for persistence in .astd files.
    /// </summary>
    public IReadOnlyList<MediaContent>? ToolMedia { get; init; }

    /// <summary>
    /// Thinking/reasoning content from the AI model (e.g., Claude extended thinking).
    /// Raises <see cref="PropertyChanged"/> when updated.
    /// </summary>
    public string? ThinkingContent
    {
        get => _thinkingContent;
        set => SetField(ref _thinkingContent, value);
    }

    #endregion

    #region Tree Properties

    /// <summary>
    /// The ID of the parent message in the conversation tree.
    /// Null for the first message (root). Used for branching support.
    /// </summary>
    public string? ParentId { get; init; }

    /// <summary>
    /// Total number of sibling messages sharing the same parent.
    /// Computed at runtime, not serialized.
    /// </summary>
    [JsonIgnore]
    public int SiblingCount { get; set; } = 1;

    /// <summary>
    /// Zero-based index among siblings sharing the same parent.
    /// Computed at runtime, not serialized.
    /// </summary>
    [JsonIgnore]
    public int SiblingIndex { get; set; }

    /// <summary>
    /// The ID of the currently active child in a branch.
    /// Used to preserve the user's branch selection across save/load.
    /// Serialized when non-null so branch navigation is restored correctly.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ActiveChildId { get; set; }

    #endregion

    #region INotifyPropertyChanged

    /// <inheritdoc/>
    public event PropertyChangedEventHandler? PropertyChanged;

    #endregion

    #region Private Methods

    /// <summary>Sets a backing field and raises <see cref="PropertyChanged"/> if the value changed.</summary>
    private void SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return;
        field = value;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    #endregion
}
