namespace FieldCure.Ai.Providers.Models;

/// <summary>
/// Reports token consumption for an AI request, including input and output counts.
/// </summary>
/// <param name="InputTokens">The number of tokens in the prompt (input).</param>
/// <param name="OutputTokens">The number of tokens generated by the model (output).</param>
public partial record TokenUsage(
    int InputTokens,
    int OutputTokens
)
{
    #region Computed Properties

    /// <summary>The combined total of input and output tokens.</summary>
    public int TotalTokens => InputTokens + OutputTokens;

    #endregion

    #region Prompt Caching (Anthropic)

    /// <summary>
    /// Tokens written to the prompt cache in this request. Null when the provider
    /// did not report cache metrics (non-Anthropic providers, or caching skipped
    /// due to minimum token threshold). Type is <see langword="long"/>? to align
    /// with the official Anthropic SDK contract.
    /// </summary>
    public long? CacheCreationInputTokens { get; init; }

    /// <summary>
    /// Tokens read from the prompt cache in this request. Null when the provider
    /// did not report cache metrics.
    /// </summary>
    public long? CacheReadInputTokens { get; init; }

    #endregion
}
